version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres-sandbox
    restart: unless-stopped
    environment:
      POSTGRES_USER: college-staff
      POSTGRES_PASSWORD: college-staff
      POSTGRES_DB: hr_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
    networks:
      - hr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U college-staff -d hr_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  hr-backend:
    image: aadeshmanandhar14646/hr-db-backend:latest 
    container_name: hr-backend-app
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: college-staff
      DB_PASSWORD: college-staff
      DB_NAME: hr_management
      DB_DIALECT: postgres
      DB_PORT: 5432
      HTTP_PORT: 5000
      secret: hr_management_jwt_secret_key_2024_super_secure_random_string
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hr-network

volumes:
  postgres_data:

networks:
  hr-network:
    driver: bridge
